# Generated by Django 2.2 on 2019-04-08 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=7)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crashbin_app.Bin')),
                ('labels', models.ManyToManyField(to='crashbin_app.Label')),
            ],
        ),
        migrations.AddField(
            model_name='bin',
            name='labels',
            field=models.ManyToManyField(to='crashbin_app.Label'),
        ),
        migrations.AddField(
            model_name='bin',
            name='maintainers',
            field=models.ManyToManyField(related_name='maintained_bins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bin',
            name='related_bins',
            field=models.ManyToManyField(related_name='_bin_related_bins_+', to='crashbin_app.Bin'),
        ),
        migrations.AddField(
            model_name='bin',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed_bins', to=settings.AUTH_USER_MODEL),
        ),
    ]
