# Generated by Django 2.2 on 2019-04-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("crashbin_app", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="report",
            name="title",
            field=models.CharField(default="Untitled", max_length=255),
            preserve_default=False,
        )
    ]
