# Generated by Django 2.2 on 2019-04-11 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crashbin_app', '0002_report_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='crashbin_app.Bin'),
        ),
    ]
