# Generated by Django 2.2.1 on 2019-05-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("crashbin_app", "0005_use_inbox")]

    operations = [
        migrations.AddField(
            model_name="bin",
            name="is_archived",
            field=models.BooleanField(default=False),
        )
    ]
