# Generated by Django 2.2.1 on 2019-05-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crashbin_app', '0006_bin_is_archived'),
        ('crashbin_app', '0006_add_messages'),
    ]

    operations = [
    ]
